name: Scrape and Push Data

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run scraper
      run: node scraper.js

    - name: Upload debug files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debug-files
        path: |
          debug.html
          final-screenshot.png
