name: Puppeteer Scraper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libappindicator3-1 \
            libasound2 \
            libatspi2.0-0 \
            libcurl4 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libicu67 \
            libpangocairo-1.0-0 \
            libpci3 \
            libwayland-client0 \
            libxss1 \
            libxtst6 \
            fonts-liberation \
            libappindicator3-1 \
            libnss3 \
            xdg-utils \
            lsb-release \
            sudo \
            wget \
            ca-certificates

      - name: Install dependencies
        run: npm install

      - name: Run the scraper
        run: node scraper.js
