name: Scrape Data and Save to Files

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  scrape:
    runs-on: ubuntu-latest  # Ubuntu environment for GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure you are using a Node.js version compatible with Puppeteer

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Run scraper.js
        run: |
          node scraper.js  # This will execute your scraper script

      - name: Upload JSON output files
        uses: actions/upload-artifact@v2
        with:
          name: json-files
          path: |
            prematch.json
            live.json
