name: Scrape and Push Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'    # >=16 is required for '??=' support

      - name: Install dependencies
        run: npm install

      - name: Install Chrome for Puppeteer
        run: |
          sudo apt update
          sudo apt install -y wget gnupg2
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub \
            | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run scraper
        run: |
          export PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"
          node scraper.js

      - name: Upload debug files (if any)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-info
          path: |
            debug.html
            final-screenshot.png

      - name: Commit & push results
        if: success()
        run: |
          git config --global user.name "Malish Dissanayake"
          git config --global user.email "malishadr946@gmail.com"
          git add prematch.json live.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
